Repository kubeedge/sedna, pull requests merged in 2021-08, with the labels that each got.

#100 Add object search and tracking proposals
  build/crd-samples/sedna/objectsearchservice_v1alpha1.yaml
  build/crd-samples/sedna/objecttrackingservice_v1alpha1.yaml
  docs/proposals/images/object-search-components.png
  docs/proposals/images/object-search-controller.png
  docs/proposals/images/object-search-downstream-controller.png
  docs/proposals/images/object-search-flow-creation.png
  docs/proposals/images/object-search-service-crd.png
  docs/proposals/images/object-search-upstream-controller.png
  docs/proposals/images/object-search-worker-communication.png
  docs/proposals/images/object-tracking-components.png
  docs/proposals/images/object-tracking-controller.png
  docs/proposals/images/object-tracking-downstream-controller.png
  docs/proposals/images/object-tracking-flow-creation.png
  docs/proposals/images/object-tracking-service-crd.png
  docs/proposals/images/object-tracking-upstream-controller.png
  docs/proposals/images/object-tracking-worker-communication.png
  docs/proposals/object-search.md
  docs/proposals/object-tracking.md
  pkg/apis/sedna/v1alpha1/common_types.go
  pkg/apis/sedna/v1alpha1/objectsearchservice_types.go
  pkg/apis/sedna/v1alpha1/objecttrackingservice_types.go
Labels: approved, lgtm, size/XL

#146 Fix the problem that kbimage cannot be compiled in Makefile
  Makefile
Labels: approved, lgtm, size/S

#134 gm: decouple all features into independent package
  cmd/sedna-gm/app/controller.go
  cmd/sedna-gm/sedna-gm.go
  pkg/globalmanager/controller.go
  pkg/globalmanager/controllers/dataset/dataset.go
  pkg/globalmanager/controllers/dataset/downstream.go
  pkg/globalmanager/controllers/dataset/upstream.go
  pkg/globalmanager/controllers/federatedlearning/downstream.go
  pkg/globalmanager/controllers/federatedlearning/federatedlearningjob.go
  pkg/globalmanager/controllers/federatedlearning/upstream.go
  pkg/globalmanager/controllers/incrementallearning/downstream.go
  pkg/globalmanager/controllers/incrementallearning/incrementallearningjob.go
  pkg/globalmanager/controllers/incrementallearning/upstream.go
  pkg/globalmanager/controllers/jointinference/downstream.go
  pkg/globalmanager/controllers/jointinference/jointinferenceservice.go
  pkg/globalmanager/controllers/jointinference/upstream.go
  pkg/globalmanager/controllers/lifelonglearning/downstream.go
  pkg/globalmanager/controllers/lifelonglearning/lifelonglearningjob.go
  pkg/globalmanager/controllers/lifelonglearning/upstream.go
  pkg/globalmanager/controllers/manager.go
  pkg/globalmanager/controllers/registry.go
  pkg/globalmanager/controllers/upstream.go
  pkg/globalmanager/downstream.go
  pkg/globalmanager/runtime/common.go
  pkg/globalmanager/runtime/secret_injector.go
  pkg/globalmanager/runtime/storage_initializer_injector.go
  pkg/globalmanager/runtime/types.go
  pkg/globalmanager/runtime/worker.go
  pkg/globalmanager/types.go
  pkg/globalmanager/upstream.go
  pkg/localcontroller/manager/incrementallearningjob.go
Labels: approved, lgtm, size/XXL

#107 [incremental learning] example:keep all results whether is hardExample or not, fixed the issue of using s3 to save model
  examples/incremental_learning/helmet_detection/training/eval.py
  examples/incremental_learning/helmet_detection/training/inference.py
  examples/incremental_learning/helmet_detection/training/interface.py
  examples/incremental_learning/helmet_detection/training/train.py
  lib/sedna/algorithms/hard_example_mining/__init__.py
  lib/sedna/algorithms/hard_example_mining/hard_example_mining.py
  lib/sedna/backend/__init__.py
  lib/sedna/backend/tensorflow/__init__.py
  lib/sedna/common/config.py
  lib/sedna/core/base.py
  lib/sedna/core/incremental_learning/incremental_learning.py
Labels: approved, lgtm, size/L

#143 improve lifelong learning docs
  build/crd-samples/sedna/lifelonglearningjobv1alpha1.yaml
  docs/proposals/images/lifelong-learning-controller.png
  docs/proposals/lifelong-learning.md
  examples/lifelong_learning/atcii/README.md
Labels: lgtm, approved, size/L

#117 joint_inference: bug fix and interface reconstruction
  examples/joint_inference/helmet_detection_inference/big_model/big_model.py
  examples/joint_inference/helmet_detection_inference/big_model/interface.py
  examples/joint_inference/helmet_detection_inference/little_model/interface.py
  examples/joint_inference/helmet_detection_inference/little_model/little_model.py
  lib/sedna/common/config.py
  lib/sedna/core/joint_inference/joint_inference.py
  lib/sedna/service/client.py
Labels: lgtm, approved, size/L

#149 lc: decouple all features into independent package
  cmd/sedna-lc/app/server.go
  pkg/localcontroller/gmclient/types.go
  pkg/localcontroller/manager/types.go
  pkg/localcontroller/managers/dataset/dataset.go
  pkg/localcontroller/managers/federatedlearning/federatedlearningjob.go
  pkg/localcontroller/managers/incrementallearning/incrementallearningjob.go
  pkg/localcontroller/managers/jointinference/jointinferenceservice.go
  pkg/localcontroller/managers/lifelonglearning/lifelonglearningjob.go
  pkg/localcontroller/managers/model/model.go
  pkg/localcontroller/managers/types.go
  pkg/localcontroller/server/server.go
  pkg/localcontroller/storage/storage.go
  pkg/localcontroller/worker/worker.go
Labels: lgtm, approved, size/XL

#153 Fix rendering issue of example doc in readthedocs
  examples/incremental_learning/helmet_detection/README.md
  examples/storage/s3/README.md
Labels: lgtm, approved, size/M

#142 lifelong learning: issue-driven interface-adjustment and bug fix
  examples/lifelong_learning/atcii/eval.py
  examples/lifelong_learning/atcii/inference.py
  examples/lifelong_learning/atcii/train.py
  lib/sedna/algorithms/multi_task_learning/multi_task_learning.py
  lib/sedna/algorithms/multi_task_learning/task_jobs/artifact.py
  lib/sedna/algorithms/multi_task_learning/task_jobs/task_remodeling.py
  lib/sedna/algorithms/unseen_task_detect/__init__.py
  lib/sedna/algorithms/unseen_task_detect/unseen_task_detect.py
  lib/sedna/backend/base.py
  lib/sedna/backend/tensorflow/__init__.py
  lib/sedna/common/constant.py
  lib/sedna/common/file_ops.py
  lib/sedna/core/base.py
  lib/sedna/core/lifelong_learning/lifelong_learning.py
  lib/sedna/datasources/__init__.py
  lib/sedna/service/run_kb.py
  lib/sedna/service/server/knowledgeBase/server.py
Labels: lgtm, approved, size/XL

#154 [Lifelong example]: fix the problem from backend and constant
  lib/sedna/algorithms/multi_task_learning/multi_task_learning.py
  lib/sedna/backend/base.py
  lib/sedna/core/lifelong_learning/lifelong_learning.py
Labels: lgtm, approved, size/S

#155 Push images automatically when a new release is created
  .github/workflows/image-publish.yaml
Labels: lgtm, approved, size/M

#156 docs: update install guide
  docs/setup/install.md
Labels: lgtm, approved, size/S

#152 IL: LC supports to recover job when restart
  pkg/localcontroller/db/db.go
  pkg/localcontroller/managers/incrementallearning/incrementallearningjob.go
Labels: lgtm, approved, size/XL

#158 Fix IMAGE_REPO in github image-publish action
  .github/workflows/image-publish.yaml
Labels: lgtm, approved, size/XS

#164 Support websocket reconnection when the server status is abnormal
  lib/requirements.txt
  lib/sedna/service/client.py
Labels: lgtm, approved, size/M

#166 Fix codegen verify checker
  .github/workflows/main.yaml
  hack/verify-codegen.sh
  pkg/apis/sedna/v1alpha1/zz_generated.deepcopy.go
  pkg/client/clientset/versioned/typed/sedna/v1alpha1/fake/fake_objectsearchservice.go
  pkg/client/clientset/versioned/typed/sedna/v1alpha1/fake/fake_objecttrackingservice.go
  pkg/client/clientset/versioned/typed/sedna/v1alpha1/fake/fake_sedna_client.go
  pkg/client/clientset/versioned/typed/sedna/v1alpha1/generated_expansion.go
  pkg/client/clientset/versioned/typed/sedna/v1alpha1/objectsearchservice.go
  pkg/client/clientset/versioned/typed/sedna/v1alpha1/objecttrackingservice.go
  pkg/client/clientset/versioned/typed/sedna/v1alpha1/sedna_client.go
  pkg/client/informers/externalversions/generic.go
  pkg/client/informers/externalversions/sedna/v1alpha1/interface.go
  pkg/client/informers/externalversions/sedna/v1alpha1/objectsearchservice.go
  pkg/client/informers/externalversions/sedna/v1alpha1/objecttrackingservice.go
  pkg/client/listers/sedna/v1alpha1/expansion_generated.go
  pkg/client/listers/sedna/v1alpha1/objectsearchservice.go
  pkg/client/listers/sedna/v1alpha1/objecttrackingservice.go
Labels: lgtm, approved, size/XXL

#159 update lib doc
  lib/sedna/README.md
  lib/sedna/VERSION
  lib/sedna/__version__.py
  lib/sedna/algorithms/__init__.py
  lib/sedna/algorithms/aggregation/__init__.py
  lib/sedna/algorithms/aggregation/aggregation.py
  lib/sedna/algorithms/hard_example_mining/__init__.py
  lib/sedna/algorithms/hard_example_mining/hard_example_mining.py
  lib/sedna/algorithms/multi_task_learning/__init__.py
  lib/sedna/algorithms/multi_task_learning/multi_task_learning.py
  lib/sedna/algorithms/multi_task_learning/task_jobs/__init__.py
  lib/sedna/algorithms/multi_task_learning/task_jobs/inference_integrate.py
  lib/sedna/algorithms/multi_task_learning/task_jobs/task_definition.py
  lib/sedna/algorithms/multi_task_learning/task_jobs/task_mining.py
  lib/sedna/algorithms/multi_task_learning/task_jobs/task_relation_discover.py
  lib/sedna/algorithms/multi_task_learning/task_jobs/task_remodeling.py
  lib/sedna/algorithms/unseen_task_detect/unseen_task_detect.py
  lib/sedna/backend/__init__.py
  lib/sedna/backend/tensorflow/__init__.py
  lib/sedna/common/class_factory.py
  lib/sedna/common/constant.py
  lib/sedna/common/file_ops.py
  lib/sedna/common/utils.py
  lib/sedna/core/federated_learning/federated_learning.py
  lib/sedna/core/incremental_learning/incremental_learning.py
  lib/sedna/core/joint_inference/joint_inference.py
  lib/sedna/core/lifelong_learning/lifelong_learning.py
  lib/sedna/datasources/__init__.py
  lib/sedna/service/client.py
Labels: lgtm, approved, size/XXL

#148 Add contributing docs
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  README.md
  README_zh.md
  docs/contributing/control-plane/add-a-new-synergy-feature.md
  docs/contributing/control-plane/debug-gm.md
  docs/contributing/control-plane/debug-lc.md
  docs/contributing/control-plane/development.md
  docs/contributing/getting-started.md
  docs/contributing/prepare-environment.md
Labels: lgtm, approved, size/L

#160 Update s3 example docs of IL&JI
  examples/README.md
  examples/storage/s3/incremental_learning/README.md
  examples/storage/s3/joint_inference/README.md
Labels: lgtm, approved, size/L

#174 Fix s3 example docs of IL&JI
  examples/storage/s3/incremental_learning/README.md
  examples/storage/s3/joint_inference/README.md
Labels: lgtm, approved, size/S
