Repository kubeedge/sedna, pull requests merged in 2021-04, with the labels that each got.

#37 docs: enhance example of incremental learning
  README.md
  README_zh.md
  examples/incremental-learning-helmet-detection.Dockerfile
  examples/incremental_learning/helmet_detection/README.md
  examples/incremental_learning/helmet_detection/image/effect_comparison.png
  examples/incremental_learning/helmet_detection/image/export-label.png
  examples/incremental_learning/helmet_detection/image/label-interface.png
  examples/incremental_learning/helmet_detection/image/label-result.png
  examples/incremental_learning/helmet_detection/image/make-sense.png
  examples/incremental_learning/helmet_detection/image/reverted_label.png
  examples/incremental_learning/helmet_detection/training/data_gen.py
  examples/incremental_learning/helmet_detection/training/eval.py
  examples/incremental_learning/helmet_detection/training/inference.py
  examples/incremental_learning/helmet_detection/training/interface.py
  examples/incremental_learning/helmet_detection/training/resnet18.py
  examples/incremental_learning/helmet_detection/training/train.py
  examples/incremental_learning/helmet_detection/training/validate_utils.py
  examples/incremental_learning/helmet_detection/training/yolo3_multiscale.py
  examples/incremental_learning/helmet_detection_incremental_train/README.md
Labels: approved, lgtm, size/XL

#43 Add all-in-one installation script
  docs/setup/install.md
  scripts/installation/install.sh
Labels: approved, lgtm, size/XL

#45 Fix example of federated learning
  examples/federated_learning/surface_defect_detection/README.md
Labels: approved, lgtm, size/XS

#48 Update install script
  docs/setup/install.md
  scripts/installation/install.sh
Labels: approved, lgtm, size/M

#49 Add two issue templates
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/enhancement.md
Labels: approved, lgtm, size/L

#63 gm/incrementallearningjob.go: fix wrong kind
  pkg/globalmanager/incrementallearningjob.go
Labels: approved, lgtm, size/XS

#52 Add storage-initializer code/Dockerfile
  build/crds/sedna.io_datasets.yaml
  build/crds/sedna.io_incrementallearningjobs.yaml
  build/crds/sedna.io_models.yaml
  build/gm/rbac/gm.yaml
  pkg/apis/sedna/v1alpha1/dataset_types.go
  pkg/apis/sedna/v1alpha1/incrementallearningjob_types.go
  pkg/apis/sedna/v1alpha1/model_types.go
  pkg/globalmanager/common.go
  pkg/globalmanager/downstream.go
  pkg/globalmanager/federatedlearningjob.go
  pkg/globalmanager/incrementallearningjob.go
  pkg/globalmanager/jointinferenceservice.go
  pkg/globalmanager/messagelayer/context.go
  pkg/globalmanager/messagelayer/model/model.go
  pkg/globalmanager/secret_injector.go
  pkg/globalmanager/storage_initializer_injector.go
  pkg/globalmanager/types.go
  pkg/globalmanager/worker.go
  scripts/storage-initializer/Dockerfile
  scripts/storage-initializer/README.md
  scripts/storage-initializer/build_image.sh
  scripts/storage-initializer/download.py
  scripts/storage-initializer/requirements.txt
Labels: approved, lgtm, size/XXL
