Repository kubeedge/sedna, pull requests merged in 2021-06, with the labels that each got.

#70 Fix typos/cleanups
  Makefile
  docs/setup/install.md
  hack/run-e2e.sh
  pkg/globalmanager/federatedlearningjob.go
  pkg/globalmanager/incrementallearningjob.go
Labels: approved, lgtm, size/S

#68 Fix the hard sample judge which should less than threshold_cross_entropy
  lib/sedna/hard_example_mining/image_classification/hard_mine_filters.py
Labels: approved, lgtm, size/XS

#75 unified icon style
  README.md
  README_zh.md
Labels: approved, lgtm, size/XS

#74 Fix k8s-service selector issue
  pkg/globalmanager/common.go
  pkg/globalmanager/federatedlearningjob.go
  pkg/globalmanager/jointinferenceservice.go
  pkg/globalmanager/worker.go
Labels: approved, lgtm, size/L

#76 Fall back to default volume when mounting '/'
  pkg/globalmanager/storage_initializer_injector.go
Labels: approved, lgtm, size/XS

#78 Update owners
  OWNERS
  docs/OWNERS
  examples/OWNERS
  hack/OWNERS
  lib/OWNERS
  pkg/OWNERS
  pkg/globalmanager/OWNERS
  pkg/localcontroller/OWNERS
  test/OWNERS
Labels: approved, lgtm, size/S

#79 Fixed a spelling mistake
  examples/incremental_learning/helmet_detection/README.md
Labels: approved, lgtm, size/XS

#80 add lifelong learning to architecture diagram
  docs/proposals/images/framework-zh.png
  docs/proposals/images/framework.png
Labels: approved, lgtm, size/XS

#82 Fix lifelong learning bugs
  README.md
  README_zh.md
  build/kb/Dockerfile
  lib/sedna/core/lifelong_learning/lifelong_learning.py
Labels: approved, lgtm, size/M

#81 Bump images/lib to v0.3.0
  Makefile
  examples/federated_learning/surface_defect_detection/README.md
  examples/incremental_learning/helmet_detection/README.md
  examples/joint_inference/helmet_detection_inference/README.md
  lib/sedna/VERSION
  pkg/globalmanager/storage_initializer_injector.go
  scripts/installation/install.sh
Labels: approved, lgtm, size/M

#83 examples: fix the push script ignoring first image
  examples/push_image.sh
Labels: approved, lgtm, size/XS

#84 add lifelong learning introduction in README
  README.md
  README_zh.md
Labels: approved, lgtm, size/S

#86 Optimize KB dockerfile
  build/kb/Dockerfile
Labels: approved, lgtm, size/S

#87 KB: fix wrong version in dockerfile
  build/kb/Dockerfile
Labels: approved, lgtm, size/XS

#88 Add more github issue templates
  .github/ISSUE_TEMPLATE/cleanup.md
  .github/ISSUE_TEMPLATE/documentation.md
  .github/ISSUE_TEMPLATE/question.md
Labels: approved, lgtm, size/M

#93 Add local up install doc
  docs/setup/local-up.md
Labels: approved, lgtm, size/S

#101 GM: modified worker mount mode
  pkg/globalmanager/federatedlearningjob.go
  pkg/globalmanager/incrementallearningjob.go
  pkg/globalmanager/jointinferenceservice.go
  pkg/globalmanager/lifelonglearningjob.go
  pkg/globalmanager/storage_initializer_injector.go
Labels: approved, lgtm, size/L

#109 Docs: fix path of local-up install script
  docs/setup/local-up.md
Labels: approved, lgtm, size/XS
