Repository kubeedge/sedna, pull requests merged in 2021-12, with the labels that each got.

#249 fix grammar error in globalmanager module
  pkg/globalmanager/config/config.go
  pkg/globalmanager/controllers/federatedlearning/upstream.go
  pkg/globalmanager/controllers/incrementallearning/incrementallearningjob.go
  pkg/globalmanager/controllers/incrementallearning/upstream.go
  pkg/globalmanager/controllers/jointinference/upstream.go
  pkg/globalmanager/controllers/lifelonglearning/downstream.go
  pkg/globalmanager/controllers/lifelonglearning/lifelonglearningjob.go
  pkg/globalmanager/controllers/lifelonglearning/upstream.go
  pkg/globalmanager/controllers/objectsearch/objectsearchservice.go
Labels: lgtm, approved, size/M, kind/cleanup

#247 installation: allow *_VERSION passing without `v`
  scripts/installation/all-in-one.sh
  scripts/installation/install.sh
Labels: lgtm, approved, size/XS

#255 Upgrade golang from 1.14 to 1.16
  .github/workflows/main.yaml
  build/gm/Dockerfile
  build/lc/Dockerfile
  go.mod
Labels: lgtm, approved, size/S

#253 all-in-one: add edgemesh installation
  scripts/installation/all-in-one.sh
Labels: lgtm, approved, size/L
