Repository kubeedge/sedna, pull requests merged in 2021-03, with the labels that each got.

#22 local-up.sh: no docker-image-prune to speed up
  hack/local-up.sh
Labels: approved, lgtm, size/XS

#23 docs: add the incremental learning proposal
  docs/proposals/images/incremental-learning-controller.png
  docs/proposals/images/incremental-learning-downstream-controller.png
  docs/proposals/images/incremental-learning-flow-creation.png
  docs/proposals/images/incremental-learning-flow-deploy-stage.png
  docs/proposals/images/incremental-learning-flow-eval-stage.png
  docs/proposals/images/incremental-learning-flow-train-stage.png
  docs/proposals/images/incremental-learning-job-crd-details.png
  docs/proposals/images/incremental-learning-job-crd.png
  docs/proposals/images/incremental-learning-state-machine.png
  docs/proposals/images/incremental-learning-upstream-controller.png
  docs/proposals/incremental-learning.md
Labels: approved, lgtm, size/L

#29 Update readme
  README.md
  README_zh.md
  examples/joint_inference/helmet_detection_inference/README.md
Labels: approved, lgtm, size/M

#34 local-up.sh: start kubeedge before building images
  hack/local-up.sh
Labels: approved, lgtm, size/S

#32 modify the dataset format to relative path
  examples/federated_learning/surface_defect_detection/training_worker/train.py
  examples/incremental_learning/helmet_detection_incremental_train/training/train.py
  lib/sedna/dataset/dataset.py
Labels: approved, lgtm, size/M

#33 Add pod template support
  Makefile
  build/crd-samples/sedna/federatedlearningjob_v1alpha.yaml
  build/crd-samples/sedna/federatedlearningjob_v1alpha1.yaml
  build/crd-samples/sedna/incrementallearningjob_v1alpha1.yaml
  build/crd-samples/sedna/jointinferenceservice_v1alpha1.yaml
  build/crds/sedna.io_datasets.yaml
  build/crds/sedna.io_federatedlearningjobs.yaml
  build/crds/sedna.io_incrementallearningjobs.yaml
  build/crds/sedna.io_jointinferenceservices.yaml
  build/crds/sedna.io_models.yaml
  build/crds/sedna/dataset_v1alpha1.yaml
  build/crds/sedna/federatedlearningjob_v1alpha1.yaml
  build/crds/sedna/incrementallearningjob_v1alpha1.yaml
  build/crds/sedna/jointinferenceservice_v1alpha1.yaml
  build/crds/sedna/model_v1alpha1.yaml
  cmd/sedna-lc/app/server.go
  docs/proposals/federated-learning.md
  docs/proposals/images/federated-learning-job-crd-details.png
  docs/proposals/images/incremental-learning-job-crd-details.png
  docs/proposals/images/joint-inference-service-crd-details.png
  docs/proposals/incremental-learning.md
  docs/proposals/joint-inference.md
  docs/setup/install.md
  examples/build_image.sh
  examples/federated-learning-surface-defect-detection-aggregation.Dockerfile
  examples/federated-learning-surface-defect-detection-train.Dockerfile
  examples/incremental-learning-helmet-detection.Dockerfile
  examples/joint-inference-helmet-detection-big.Dockerfile
  examples/joint-inference-helmet-detection-little.Dockerfile
  examples/push_image.sh
  hack/local-up.sh
  lib/sedna/common/config.py
  lib/sedna/context.py
  lib/sedna/dataset/dataset.py
  pkg/apis/sedna/v1alpha1/common_types.go
  pkg/apis/sedna/v1alpha1/dataset_types.go
  pkg/apis/sedna/v1alpha1/federatedlearningjob_types.go
  pkg/apis/sedna/v1alpha1/incrementallearningjob_types.go
  pkg/apis/sedna/v1alpha1/jointinferenceservice_types.go
  pkg/apis/sedna/v1alpha1/model_types.go
  pkg/apis/sedna/v1alpha1/zz_generated.deepcopy.go
  pkg/globalmanager/common.go
  pkg/globalmanager/config/config.go
  pkg/globalmanager/downstream.go
  pkg/globalmanager/federatedlearningjob.go
  pkg/globalmanager/incrementallearningjob.go
  pkg/globalmanager/jointinferenceservice.go
  pkg/globalmanager/types.go
  pkg/localcontroller/gmclient/websocket.go
  pkg/localcontroller/manager/incrementallearningjob.go
Labels: approved, lgtm, size/XXL

#41 docs: update installation instructions
  build/gm/gm-config.yaml
  docs/setup/install.md
Labels: approved, lgtm, size/L
