Repository kubeedge/sedna, pull requests merged in 2021-09, with the labels that each got.

#157 [Lib Support] hot model update
  examples/incremental_learning/helmet_detection/training/inference.py
  lib/sedna/backend/base.py
  lib/sedna/core/base.py
Labels: lgtm, approved, size/L

#182 Upgrade gorilla/websocket from v1.4.0 to v1.4.2
  go.mod
  go.sum
  vendor/github.com/gorilla/websocket/.travis.yml
  vendor/github.com/gorilla/websocket/README.md
  vendor/github.com/gorilla/websocket/client.go
  vendor/github.com/gorilla/websocket/conn.go
  vendor/github.com/gorilla/websocket/doc.go
  vendor/github.com/gorilla/websocket/go.mod
  vendor/github.com/gorilla/websocket/go.sum
  vendor/github.com/gorilla/websocket/join.go
  vendor/github.com/gorilla/websocket/prepared.go
  vendor/github.com/gorilla/websocket/proxy.go
  vendor/github.com/gorilla/websocket/server.go
  vendor/github.com/gorilla/websocket/util.go
  vendor/modules.txt
Labels: lgtm, approved, size/L

#183 fix lib/requirements
  lib/requirements.txt
Labels: lgtm, approved, size/M

#167 API&GM: FL adds transmitter interface
  build/crds/sedna.io_federatedlearningjobs.yaml
  pkg/apis/sedna/v1alpha1/federatedlearningjob_types.go
  pkg/apis/sedna/v1alpha1/zz_generated.deepcopy.go
  pkg/globalmanager/controllers/federatedlearning/federatedlearningjob.go
Labels: lgtm, approved, size/L

#185 FL: fix nil pointer bug in GM
  pkg/globalmanager/controllers/federatedlearning/federatedlearningjob.go
Labels: lgtm, approved, size/S

#186 fix env variable error in aggregation
  examples/federated_learning/surface_defect_detection/aggregation_worker/aggregate.py
  lib/sedna/service/server/aggregation.py
Labels: lgtm, approved, size/S

#187 GM: fix the bug of injecting hostpath mount
  pkg/globalmanager/runtime/storage_initializer_injector.go
Labels: lgtm, approved, size/S

#195 Optimize installation script
  scripts/installation/install.sh
Labels: lgtm, approved, size/M

#200 Increase GM memory limit from 128Mi to 256Mi
  scripts/installation/install.sh
Labels: lgtm, approved, size/XS

#201 GM: remove externalIPs when creating k8s service
  pkg/globalmanager/runtime/worker.go
Labels: lgtm, approved, size/XS

#192 Add all-in-one installation script/docs
  README.md
  docs/setup/all-in-one.md
  docs/setup/install.md
  docs/setup/local-up.md
  docs/setup/quick-start.md
  scripts/installation/all-in-one.sh
  scripts/installation/build-allinone-image.sh
Labels: lgtm, approved, size/XL

#190 Add object search controller
  pkg/globalmanager/controllers/objectsearch/downstream.go
  pkg/globalmanager/controllers/objectsearch/objectsearchservice.go
  pkg/globalmanager/controllers/objectsearch/upstream.go
  pkg/globalmanager/controllers/registry.go
  pkg/globalmanager/runtime/common.go
  pkg/globalmanager/runtime/worker.go
Labels: lgtm, approved, size/XL
