Repository kubeedge/sedna, pull requests merged in 2021-11, with the labels that each got.

#215 Fix building wrong GM/LC arm64 docker images
  Makefile
  hack/lib/buildx.sh
Labels: lgtm, approved, size/XS

#178 Update docs: add lib development guide
  build/crd-samples/sedna/lifelonglearningjobv1alpha1.yaml
  docs/contributing/lib/datasets.md
  docs/contributing/lib/development.md
  docs/contributing/lib/new_algorithm.md
  docs/contributing/prepare-environment.md
  docs/index.rst
  docs/quickstart.md
  docs/related_link.md
Labels: lgtm, approved, size/XL

#239 Fix IL bug: TrainTriggerStatus used in eval task
  pkg/localcontroller/managers/incrementallearning/incrementallearningjob.go
Labels: lgtm, approved, size/XS

#230 buildx: speed the language having builtin build
  build/gm/Dockerfile
  build/lc/Dockerfile
  hack/lib/buildx.sh
Labels: lgtm, approved, size/L

#237 Fix IL bug: job misses first data when reads data.
  pkg/localcontroller/managers/incrementallearning/incrementallearningjob.go
Labels: lgtm, approved, size/XS

#242 IL: decouple eval task and deploy task
  pkg/globalmanager/controllers/incrementallearning/downstream.go
  pkg/localcontroller/gmclient/types.go
  pkg/localcontroller/managers/incrementallearning/incrementallearningjob.go
Labels: lgtm, approved, size/L

#243 examples: fix the image name prefix
  examples/build_image.sh
Labels: lgtm, approved, size/XS

#248 fix grammar error in api module
  pkg/apis/sedna/v1alpha1/federatedlearningjob_types.go
  pkg/apis/sedna/v1alpha1/jointinferenceservice_types.go
  pkg/apis/sedna/v1alpha1/objectsearchservice_types.go
  pkg/apis/sedna/v1alpha1/objecttrackingservice_types.go
  pkg/apis/sedna/v1alpha1/register.go
Labels: lgtm, approved, size/S, kind/cleanup
