Repository kubeedge/sedna, pull requests merged in 2021-07, with the labels that each got.

#110 IL: add support of multi-node train/eval
  pkg/globalmanager/common.go
  pkg/globalmanager/downstream.go
  pkg/globalmanager/federatedlearningjob.go
  pkg/globalmanager/incrementallearningjob.go
  pkg/globalmanager/jointinferenceservice.go
  pkg/globalmanager/lifelonglearningjob.go
  pkg/globalmanager/types.go
  pkg/localcontroller/manager/incrementallearningjob.go
Labels: approved, lgtm, size/XL

#121 install.sh: fix LC_BIND_PORT bug
  scripts/installation/install.sh
Labels: approved, lgtm, size/XS

#106 fix federated learning bugs
  examples/federated_learning/surface_defect_detection/aggregation_worker/aggregate.py
  examples/federated_learning/surface_defect_detection/training_worker/inference.py
  examples/federated_learning/surface_defect_detection/training_worker/train.py
  lib/sedna/__init__.py
  lib/sedna/algorithms/aggregation/__init__.py
  lib/sedna/algorithms/aggregation/aggregation.py
  lib/sedna/backend/tensorflow/__init__.py
  lib/sedna/core/__init__.py
  lib/sedna/core/federated_learning/federated_learning.py
  lib/sedna/service/client.py
  lib/sedna/service/server/aggregation.py
  lib/sedna/service/server/base.py
Labels: approved, lgtm, size/L

#139 LC: fix nil pointer dereference bug
  pkg/localcontroller/manager/incrementallearningjob.go
Labels: approved, lgtm, size/XS

#137 LC: send dataset update to GM only when changed
  pkg/localcontroller/manager/dataset.go
Labels: approved, lgtm, size/S
