Repository kubeedge/sedna, pull requests merged in 2022-10, with the labels that each got.

#340 [OSPP] The proposal for Observability management
  docs/proposals/images/observability-management-architecture.png
  docs/proposals/observability-management.md
Labels: lgtm, approved, kind/design, size/L

#335 [OSPP] The proposal for Lifelong Learning O&M
  docs/proposals/Lifelong-learning-Ops-ui.md
  docs/proposals/images/lifelong-learning-ops-architecture.png
  docs/proposals/images/lifelong-learning-ops-custom-metrics-values.png
  docs/proposals/images/lifelong-learning-ops-custom-metrics.png
  docs/proposals/images/lifelong-learning-ops-log-grafana.png
  docs/proposals/images/lifelong-learning-ops-metrics-grafana.png
Labels: lgtm, approved, kind/design, size/L

#373 Add components folder
  components/dashboard/README.md
Labels: lgtm, approved, size/XS

#366 [OSPP] The implementation for Observability management
  components/dashboard/README.md
  components/dashboard/exporter/incremental_learning/hard_samples_exporter.py
  components/dashboard/exporter/joint_inference/hard_samples_exporter.py
  components/dashboard/grafana/dashboards/Algorithm Metrics(Federated Learning).json
  components/dashboard/grafana/dashboards/Algorithm Metrics(Incremental Learning).json
  components/dashboard/grafana/dashboards/Algorithm Metrics(Joint Inference).json
  components/dashboard/grafana/dashboards/Common System Metrics.json
  components/dashboard/grafana/values.yaml
  components/dashboard/images/dashboards.png
  components/dashboard/images/demo.png
  components/dashboard/images/kube-state-metrics_up.png
  components/dashboard/images/sedna_exporter_up.png
  components/dashboard/kube-state-metrics/values.yaml
  components/dashboard/loki-stack/values.yaml
  components/dashboard/prometheus/values.yaml
  components/dashboard/setup/observability_management.md
Labels: kind/feature, lgtm, approved, size/XXL

#369 ospp Lifelong Learning exporter and Visualization
  components/dashboard/exporter/kb_exporter/go.mod
  components/dashboard/exporter/kb_exporter/main.go
  components/dashboard/grafana/dashboards/lifelonglearningjob.json
  components/dashboard/images/dashboard_import.png
  components/dashboard/images/metrics.png
  components/dashboard/images/metrics_values.png
  components/dashboard/images/precission.png
  components/dashboard/images/recall.png
  components/dashboard/images/total_dashboard.png
  components/dashboard/setup/Lifelonglearning_dashboard.md
Labels: kind/feature, lgtm, approved, size/XXL

#376 [OSPP]Mindspore demo
  examples/incremental-learning-dog-croissants-classification.Dockerfile
  examples/incremental_learning/dog_croissants_classification/README.md
  examples/incremental_learning/dog_croissants_classification/dog_croissants_classification.yaml
  examples/incremental_learning/dog_croissants_classification/training/dataset.py
  examples/incremental_learning/dog_croissants_classification/training/eval.py
  examples/incremental_learning/dog_croissants_classification/training/inference.py
  examples/incremental_learning/dog_croissants_classification/training/interface.py
  examples/incremental_learning/dog_croissants_classification/training/mobilenet_v2.py
  examples/incremental_learning/dog_croissants_classification/training/train.py
  lib/sedna/algorithms/hard_example_mining/hard_example_mining.py
  lib/sedna/backend/base.py
  lib/sedna/backend/mindspore/__init__.py
Labels: kind/feature, lgtm, approved, size/XL

#375 Add JSON data parse
  lib/sedna/datasources/__init__.py
Labels: lgtm, approved, size/L

#368 Build a high-frequency Sedna-based end-to-end use case in ModelBox fo…
  examples/incremental_learning_modelbox/mnist/Build_image.md
  examples/incremental_learning_modelbox/mnist/README.md
Labels: lgtm, approved, size/L

#341 [OSPP]The proposal for TinyMS support in Python SDK
  docs/proposals/images/tinyms-support-architecture.png
  docs/proposals/images/tinyms-support-set_bakcend.png
  docs/proposals/tinyms-support.md
Labels: kind/feature, lgtm, approved, size/L
