Repository kubeedge/sedna, pull requests merged in 2022-06, with the labels that each got.

#297 Add sedna installation helm charts
  build/helm/sedna/.helmignore
  build/helm/sedna/Chart.yaml
  build/helm/sedna/README.md
  build/helm/sedna/charts/gm/Chart.yaml
  build/helm/sedna/charts/gm/templates/configmap.yaml
  build/helm/sedna/charts/gm/templates/deployment.yaml
  build/helm/sedna/charts/gm/templates/service.yaml
  build/helm/sedna/charts/gm/values.yaml
  build/helm/sedna/charts/kb/.helmignore
  build/helm/sedna/charts/kb/Chart.yaml
  build/helm/sedna/charts/kb/templates/deployment.yaml
  build/helm/sedna/charts/kb/templates/service.yaml
  build/helm/sedna/charts/kb/values.yaml
  build/helm/sedna/charts/lc/Chart.yaml
  build/helm/sedna/charts/lc/templates/daemonset.yaml
  build/helm/sedna/charts/lc/values.yaml
  build/helm/sedna/crds/sedna.io_datasets.yaml
  build/helm/sedna/crds/sedna.io_federatedlearningjobs.yaml
  build/helm/sedna/crds/sedna.io_incrementallearningjobs.yaml
  build/helm/sedna/crds/sedna.io_jointinferenceservices.yaml
  build/helm/sedna/crds/sedna.io_lifelonglearningjobs.yaml
  build/helm/sedna/crds/sedna.io_models.yaml
  build/helm/sedna/crds/sedna.io_objectsearchservices.yaml
  build/helm/sedna/crds/sedna.io_objecttrackingservices.yaml
  build/helm/sedna/templates/NOTES.txt
  build/helm/sedna/templates/rbac.yaml
  build/helm/sedna/values.yaml
Labels: kind/feature, lgtm, approved, size/XXL

#314 Add Multi Edge Inference feature proposal
  docs/proposals/images/multi-edge-inference-arch.png
  docs/proposals/images/multi-edge-inference-controller.png
  docs/proposals/images/multi-edge-inference-crd.png
  docs/proposals/images/multi-edge-inference-downstream-controller.png
  docs/proposals/images/multi-edge-inference-upstream-controller.png
  docs/proposals/multi-edge-inference.md
Labels: lgtm, approved, size/L

#313 update DirectoryorCreate to DirectoryOrCreate
  examples/incremental_learning/helmet_detection/README.md
  examples/incremental_learning/helmet_detection/helmet_detection.yaml
  examples/storage/s3/joint_inference/README.md
  pkg/localcontroller/managers/dataset/dataset.go
Labels: lgtm, approved, size/S

#315 IL supports multipile device soc versions
  build/crds/sedna.io_incrementallearningjobs.yaml
  build/crds/sedna.io_models.yaml
  pkg/apis/sedna/v1alpha1/incrementallearningjob_types.go
  pkg/apis/sedna/v1alpha1/model_types.go
  pkg/apis/sedna/v1alpha1/zz_generated.deepcopy.go
  pkg/globalmanager/controllers/incrementallearning/downstream.go
  pkg/globalmanager/runtime/types.go
  pkg/localcontroller/managers/incrementallearning/incrementallearningjob.go
Labels: lgtm, approved, size/L

#319 Add missed files in ReID feature merge and fix Docker images name.
  examples/build_image.sh
  examples/multi-edge-inference-pedestrian-tracking-feature-extraction.Dockerfile
  examples/multi-edge-inference-pedestrian-tracking-gpu-feature-extraction.Dockerfile
  examples/multi-edge-inference-pedestrian-tracking-gpu-videoanalytics.Dockerfile
  examples/multi-edge-inference-pedestrian-tracking-reid.Dockerfile
  examples/multi-edge-inference-pedestrian-tracking-videoanalytics.Dockerfile
  examples/multiedgeinference/pedestrian_tracking/README.md
  examples/multiedgeinference/pedestrian_tracking/yaml/feature-extraction-service.yaml
  examples/multiedgeinference/pedestrian_tracking/yaml/reid-job.yaml
  examples/multiedgeinference/pedestrian_tracking/yaml/video-analytics-job.yaml
  pkg/globalmanager/runtime/storage_initializer_injector.go
  pkg/globalmanager/runtime/worker.go
Labels: lgtm, approved, kind/cleanup, size/L

#325 Fix regression bug in JobBase class.
  lib/sedna/core/base.py
Labels: kind/bug, lgtm, approved, size/XS
