Repository kubeedge/sedna, pull requests merged in 2022-08, with the labels that each got.

#343 LL: initial container can download label file
  pkg/localcontroller/util/util.go
Labels: lgtm, approved, size/XS

#346 Fix the bug: download cc multiple times in buildx
  hack/lib/buildx.sh
Labels: lgtm, approved, size/XS

#348 Fix bug: pods can not connect to kb in LL
  pkg/globalmanager/controllers/lifelonglearning/lifelonglearningjob.go
  pkg/globalmanager/runtime/worker.go
Labels: lgtm, approved, size/XS

#345 Add key envs for train worker in LL
  pkg/globalmanager/controllers/lifelonglearning/lifelonglearningjob.go
Labels: lgtm, approved, size/M

#338 Add check pylint script
  Makefile
  hack/make-rules/pylint.sh
Labels: lgtm, approved, size/M

#350 Code check and base model improvement of unstructured lifelong learning framework
  examples/lifelong_learning/RFNet/basemodel.py
  examples/lifelong_learning/RFNet/dataloaders/utils.py
  examples/lifelong_learning/RFNet/eval.py
  examples/lifelong_learning/RFNet/predict.py
  examples/lifelong_learning/RFNet/sedna_evaluate.py
  examples/lifelong_learning/RFNet/sedna_predict.py
  examples/lifelong_learning/RFNet/sedna_train.py
  examples/lifelong_learning/RFNet/train.py
  lib/sedna/algorithms/knowledge_management/edge_knowledge_management.py
  lib/sedna/algorithms/seen_task_learning/seen_task_learning.py
  lib/sedna/algorithms/seen_task_learning/task_allocation/task_allocation_by_origin.py
  lib/sedna/algorithms/seen_task_learning/task_definition/task_definition_by_origin.py
  lib/sedna/core/lifelong_learning/lifelong_learning.py
  lib/sedna/datasources/__init__.py
  lib/sedna/service/server/knowledgeBase/server.py
Labels: lgtm, approved, size/L
