Repository kubeedge/sedna, pull requests merged in 2022-07, with the labels that each got.

#327 Move algorithm-specific dependencies into class definition (optical flow)
  lib/requirements.dev.txt
  lib/sedna/algorithms/optical_flow/__init__.py
Labels: kind/bug, lgtm, approved, size/M

#331 Update e2e test script
  hack/run-e2e.sh
Labels: lgtm, approved, size/S

#332 Fix kb not starting normally after installation
  lib/sedna/algorithms/__init__.py
Labels: kind/bug, lgtm, approved, size/XS
